<div class="block" >
<?php 
    echo __('User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities
    User rules and responsibilitiesUser rules and responsibilitiesUser rules and responsibilities');
?>
</div>